import { pgTable, integer, text, boolean, uuid } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'
import { timestamps } from './helpers'
import { user } from './user'
import { recurringPayment } from './recurringPayment'
import { paymentsToTags } from './paymentsToTags'

export const payment = pgTable('Payment', {
	id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
	amount: integer('amount').notNull(),
	note: text('note'),
	// Set when this payment was generated by a recurring rule; payments outlive their rule.
	recurringPaymentId: integer('recurringPaymentId').references(() => recurringPayment.id, { onDelete: 'set null' }),
	// Review marker for rule-generated payments (they start false); purely cosmetic —
	// unconfirmed payments still count in every total. Manual payments are always true.
	confirmed: boolean('confirmed').notNull().default(true),
	...timestamps,
	userId: uuid('userId')
		.notNull()
		.references(() => user.id)
})
export const paymentsRelations = relations(payment, ({ one, many }) => ({
	user: one(user, {
		fields: [payment.userId],
		references: [user.id]
	}),
	paymentsToTags: many(paymentsToTags),
	recurringPayment: one(recurringPayment, {
		fields: [payment.recurringPaymentId],
		references: [recurringPayment.id]
	})
}))
