import {
	pgTable,
	pgEnum,
	uuid,
	varchar,
	timestamp,
	integer,
	text,
	primaryKey,
	date,
	unique,
	boolean,
	index
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

export const timestamps = {
	createdAt: timestamp('createdAt').notNull().defaultNow(),
	updatedAt: timestamp('updatedAt')
		.notNull()
		.defaultNow()
		.$onUpdate(() => new Date())
}

export const user = pgTable('User', {
	id: uuid('id').primaryKey().defaultRandom(),
	username: varchar('username', { length: 255 }).notNull().unique(),
	// Nullable: set only on OAuth-created accounts (from a verified provider email) and
	// used to auto-link OAuth logins. Password accounts have no email.
	email: varchar('email', { length: 255 }).unique(),
	passwordHash: varchar('passwordHash', { length: 255 }),
	...timestamps
})
export const usersRelations = relations(user, ({ many }) => ({
	oauthAccounts: many(oauthAccount),
	payments: many(payment),
	tags: many(tag),
	budgets: many(budget),
	sessions: many(session),
	recurringPayments: many(recurringPayment)
}))

export const payment = pgTable('Payment', {
	id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
	amount: integer('amount').notNull(),
	note: text('note'),
	// Set when this payment was generated by a recurring rule; payments outlive their rule.
	recurringPaymentId: integer('recurringPaymentId').references(() => recurringPayment.id, { onDelete: 'set null' }),
	// Review marker for rule-generated payments (they start false); purely cosmetic —
	// unconfirmed payments still count in every total. Manual payments are always true.
	confirmed: boolean('confirmed').notNull().default(true),
	...timestamps,
	userId: uuid('userId')
		.notNull()
		.references(() => user.id)
})
export const paymentsRelations = relations(payment, ({ one, many }) => ({
	user: one(user, {
		fields: [payment.userId],
		references: [user.id]
	}),
	paymentsToTags: many(paymentsToTags),
	recurringPayment: one(recurringPayment, {
		fields: [payment.recurringPaymentId],
		references: [recurringPayment.id]
	})
}))

export const recurringIntervalEnum = pgEnum('RecurringInterval', ['weekly', 'monthly', 'yearly', 'daily'])

export const recurringPayment = pgTable(
	'RecurringPayment',
	{
		id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
		amount: integer('amount').notNull(),
		note: text('note'),
		interval: recurringIntervalEnum('interval').notNull(),
		intervalCount: integer('intervalCount').notNull().default(1),
		// The anchor: the first occurrence fires ON startDate, and all later
		// occurrences are computed from it (see src/lib/recurrence.ts).
		startDate: timestamp('startDate').notNull(),
		nextRunAt: timestamp('nextRunAt').notNull(),
		endDate: timestamp('endDate'),
		paused: boolean('paused').notNull().default(false),
		// Fixed (false): occurrences stay on the calendar anchor — rent on the 1st.
		// Rolling (true): each cycle re-anchors to the actual payment date — quota subs;
		// pay early/late and the schedule follows (see reanchorRollingRule).
		rolling: boolean('rolling').notNull().default(false),
		...timestamps,
		userId: uuid('userId')
			.notNull()
			.references(() => user.id)
	},
	(table) => ({
		userNextRun: index('RecurringPayment_userId_nextRunAt_idx').on(table.userId, table.nextRunAt)
	})
)
export const recurringPaymentsRelations = relations(recurringPayment, ({ one, many }) => ({
	user: one(user, {
		fields: [recurringPayment.userId],
		references: [user.id]
	}),
	recurringPaymentsToTags: many(recurringPaymentsToTags),
	payments: many(payment)
}))

export const recurringPaymentsToTags = pgTable(
	'_RecurringPaymentToTag',
	{
		recurringPaymentId: integer('A')
			.notNull()
			.references(() => recurringPayment.id),
		tagId: integer('B')
			.notNull()
			.references(() => tag.id)
	},
	(table) => ({
		pk: primaryKey({ columns: [table.recurringPaymentId, table.tagId] })
	})
)
export const recurringPaymentsToTagsRelations = relations(recurringPaymentsToTags, ({ one }) => ({
	recurringPayment: one(recurringPayment, {
		fields: [recurringPaymentsToTags.recurringPaymentId],
		references: [recurringPayment.id]
	}),
	tag: one(tag, {
		fields: [recurringPaymentsToTags.tagId],
		references: [tag.id]
	})
}))

export const tag = pgTable(
	'Tag',
	{
		id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
		name: varchar('name', { length: 255 }).notNull(),
		color: varchar('color', { length: 32 }).notNull().default('sage'),
		icon: varchar('icon', { length: 64 }).notNull().default('Tag'),
		// Optional per-tag monthly budget, in whole dollars.
		budget: integer('budget'),
		userId: uuid('userId')
			.notNull()
			.references(() => user.id)
	},
	(table) => ({
		namePerUser: unique('Tag_userId_name_unique').on(table.userId, table.name)
	})
)
export const tagsRelations = relations(tag, ({ many, one }) => ({
	paymentsToTags: many(paymentsToTags),
	recurringPaymentsToTags: many(recurringPaymentsToTags),
	user: one(user, {
		fields: [tag.userId],
		references: [user.id]
	})
}))

export const paymentsToTags = pgTable(
	'_PaymentToTag',
	{
		paymentId: integer('A')
			.notNull()
			.references(() => payment.id),
		tagId: integer('B')
			.notNull()
			.references(() => tag.id)
	},
	(table) => ({
		pk: primaryKey({ columns: [table.paymentId, table.tagId] })
	})
)
export const paymentsToTagsRelations = relations(paymentsToTags, ({ one }) => ({
	payment: one(payment, {
		fields: [paymentsToTags.paymentId],
		references: [payment.id]
	}),
	tag: one(tag, {
		fields: [paymentsToTags.tagId],
		references: [tag.id]
	})
}))

// A budget is an overall monthly spending cap over a [startMonth, endMonth] range.
// endMonth may be null (open-ended). Amounts are whole dollars.
export const budget = pgTable('Budget', {
	id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
	amount: integer('amount').notNull(),
	startMonth: date('startMonth', { mode: 'date' }).notNull(),
	endMonth: date('endMonth', { mode: 'date' }),
	...timestamps,
	userId: uuid('userId')
		.notNull()
		.references(() => user.id)
})
export const budgetsRelations = relations(budget, ({ one }) => ({
	user: one(user, {
		fields: [budget.userId],
		references: [user.id]
	})
}))

// One row per (provider, account) pair. A user may link several providers, so the
// identity is the composite (provider, providerUserId) — not a synthetic id.
export const oauthAccount = pgTable(
	'Oauth_account',
	{
		provider: varchar('provider', { length: 32 }).notNull(), // 'google' | 'github'
		providerUserId: varchar('provider_user_id', { length: 255 }).notNull(),
		userId: uuid('userId')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' })
	},
	(table) => ({
		pk: primaryKey({ columns: [table.provider, table.providerUserId] })
	})
)
export const oauthAccountsRelations = relations(oauthAccount, ({ one }) => ({
	user: one(user, {
		fields: [oauthAccount.userId],
		references: [user.id]
	})
}))

export const session = pgTable('Session', {
	id: varchar('id', { length: 255 }).primaryKey(),
	expiresAt: timestamp('expiresAt').notNull(),
	userId: uuid('userId')
		.notNull()
		.references(() => user.id, { onDelete: 'cascade' })
})
export const sessionsRelations = relations(session, ({ one }) => ({
	user: one(user, {
		fields: [session.userId],
		references: [user.id]
	})
}))
